### ISSUE TITLE
Server crashing after last L4D2 update (14 May 2024)

### ISSUE THREAD

**Issue by BRU7U5** [fdxx/l4dtoolz#1]
Hello!

Can you check your extension? After last update i found that this extension causes server crashing. When i turns off this extension my server loading and working good with last Metamod and Sourcemod builds.

Thanks!

**Comment by fdxx** [comment]
try [v0.4.1](https://github.com/fdxx/l4dtoolz/releases/tag/v0.4.1)

**Comment by BRU7U5** [comment]
Everything is working now! Thank you so much for such a quick solution and response!
